### ISSUE TITLE
Unable to add new (permission) roles

### ISSUE THREAD

**Issue by sreichel** [magento-hackathon/CopyStoreData#2]
Fatal error: Class 'Mage_Copystoredata_Helper_Data' not found

In app\code\community\Hackathon\CopyStoreData\etc\adminhtml.xml it schould be 

```
<copystoredata translate="title" module="hackathon_copystoredata">
```

instead of

```
<copystoredata translate="title" module="copystoredata">
```

**Comment by toonvd** [comment]
You are always welcome to make pullrequests, this is a hackathon project, it will not actively be maintained unless Firegento takes interest I guess.
